DataDog/terraform-module-datadog-agentless-scanner

README.md
examples/custom_vpc/README.md
examples/single_region/README.md
modules/agentless-scanner-role/README.md
modules/agentless-scanner-role/outputs.tf
modules/agentless-scanner-role/variables.tf
modules/instance/README.md
modules/instance/outputs.tf
modules/scanning-delegate-role/main.tf
modules/user_data/README.md
modules/user_data/templates/install.sh.tftpl
modules/vpc/README.md
modules/vpc/outputs.tf
outputs.tf

This is a follow-up to [PR #14](https://github.com/DataDog/terraform-datadog-agentless-scanner/pull/14). We (on the Docs Team) had a ticket to do an editorial review of the content, but the PR got merged before I could finish it. This PR changes "agentless-scanner" to "agentless scanner" where appropriate.

Doc update: Change agentless-scanner to agentless scanner

---

modules/instance/README.md
modules/instance/main.tf
modules/instance/outputs.tf
modules/instance/variables.tf
modules/user_data/README.md
modules/user_data/variables.tf
variables.tf

Create the EC2 instance in an auto-scaling group of size 1 by default. This ensures that:
* When (not if) the underlying AWS hardware fails, a new instance is automatically spin up
* It's easy to renew instances by simply stopping one
Tagging works a bit differently with ASGs, but it's still working as expected:
(https://datadoghq.atlassian.net/browse/COMM-1733)

Create EC2 instance in ASG

---

modules/user_data/README.md
modules/user_data/variables.tf

This change bumps agentless-scanner to version `7.50-agentless-scanner-2024010901`.

Bump agentless-scanner version to 7.50-agentless-scanner-2024010901

---

modules/instance/README.md
modules/instance/main.tf
modules/instance/variables.tf

Launch template now allow dynamic reference to SSM parameters. This can allow us to have automated upgrade of our baseline image, using a `max_instance_lifetime` in our AutoScalingGroup.

ASG: add instance lifetime and SSM in launchtemplate for auto AMI upgrade

---

modules/user_data/README.md
modules/user_data/variables.tf

This change bumps `agentless-scanner` version to `7.50.0-agentless-scanner-2024011701`.

Bump agentless-scanner version to 7.50.0-agentless-scanner-2024011701

---

examples/single_region/main.tf
modules/instance/main.tf

- `scanner_role` variable in now `scanner_roles`
- add ignore_failed_scaling_activities when creating ASG: got bit by this issue when deploying on my own account

Fix single-region example

---

modules/scanning-delegate-role/main.tf

Use the same condition as we have on EBS to forbid scanning lambdas.

Forbid scanning lambdas with DatadogAgentlessScanner:false

---

modules/scanning-delegate-role/main.tf

Delegate role must be created after the scanner role has been created, otherwise when referencing the ARN in the trust policy, AWS will replace it with an unique ID not matching the role we want to allow.
>You can include the ARN for a specific role or user in the Principal element of a role trust policy. When you save the policy, AWS transforms the ARN to a unique principal ID. This helps mitigate the risk of someone escalating their privileges by removing and recreating the role or user. You don't normally see this ID in the console, because there is also a reverse transformation back to the ARN when the trust policy is displayed. However, if you delete the role or user, then the relationship is broken. The policy no longer applies, even if you recreate the user or role because it does …

Use matching arn instead of resource to fix issue with order creation

---

modules/scanning-delegate-role/main.tf

This change fixes a syntax error in scanning-delegate-role module.
```
│ Error: Incorrect attribute value type
│
│   on ../../modules/scanning-delegate-role/main.tf line 237, in data "aws_iam_policy_document" "assume_role_policy":
│  237:       identifiers = "*"
│
│ Inappropriate value for attribute "identifiers": set of string required.
```

Fix syntax error in scanning-delegate-role module

---

CHANGELOG.md
modules/user_data/README.md
modules/user_data/templates/install.sh.tftpl
modules/user_data/variables.tf

This change bumps `agentless-scanner` version to `7.50.0-agentless-scanner-2024020101`.

Bump agentless-scanner version to 7.50.0-agentless-scanner-2024020101

---

cloudformation/main.yaml
main.tf
modules/user_data/README.md
modules/user_data/main.tf
modules/user_data/templates/install.sh.tftpl
modules/user_data/variables.tf
variables.tf

This change installs the standalone `agentless-scanner` package from the beta channel of the staging repository, along with the latest version of the agent from the production repository.
Please deploy and test this change before merging.

Install standalone agentless-scanner package

---

cloudformation/main.yaml
modules/user_data/templates/install.sh.tftpl

`nbd` module was not enabled and loaded properly from our cloud-init

Enable nbd module in cloud-init

---

CHANGELOG.md
cloudformation/deploy.sh
cloudformation/main.yaml

- Inline some JSON policies into YAML
- Add a deploy script example
- Rename some resources
- Add tags on launch templates
- Allow deploying scanner inside an existing VPC with the new optional parameters: `ScannerVPCId` and `ScannerSubnetId`
- Allow associating an existing security-group to the scanner with the new optional parameter: `ScannerSecurityGroupId`
- Allow attaching an existing SSH key-pair to the scanner with the new optional parameter: `ScannerSSHKeyPairName`
- Allow setting the Datadog API Key via SecretManager with thew new optional paramater: `DatadogAPIKeySecretArn`
- Creating a dedicated security-group by default with empty ingress rules
- Add support for offline mode to scan without remote-config (deactived by default)
- AutoScalingGroup update policy replacing …

Improving CloudFormation capabilities

---

CHANGELOG.md
modules/scanning-delegate-role/README.md
modules/scanning-delegate-role/main.tf

Also: Split delegate role policies in two: orchestrator (write) and worker (read)

Add missing CopySnapshot permissions for scanning AMIs

---

README.md

We are moving to use the following name: 
`terraform-module-datadog-agentless-scanner`

Update repo name

---

cloudformation/main.yaml

CF does not allow for optional typed arguments. Let's rely on `String`s with a pattern.

CloudFormation: fix deployment with VPC creation

---

.gitignore
CHANGELOG.md
examples/custom_vpc/main.tf
examples/custom_vpc/variables.tf
main.tf
modules/instance/README.md
modules/instance/main.tf
modules/instance/variables.tf

TF: enforce the creation of a dedicated security-group for the scanner instead of relying on the VPC default one. This required adding a new parameter to the `instance` module to pass the VPC: `vpc_id`.

Terraform: avoid using default security-group for scanner

---

cloudformation/main.yaml
modules/agentless-scanner-role/main.tf

Tighten the `DatadogAgentlessScannerAgentRole` by adding a condition on its trust relationship. 
This condition would prevent an attacker with only the `iam:PassRole` and `ec2:RunInstances` permissions (and not `ec2:CreateTags`) to abuse the highly privileged role that is DatadogAgentlessScannerAgentRole.

Restrict scanner role trust policy to instance with the scanner tags

---

main.tf
modules/instance/README.md
modules/instance/main.tf
modules/instance/variables.tf
modules/vpc/README.md
modules/vpc/main.tf
modules/vpc/outputs.tf

This PR add the creation of multiple subnets for a maximum of 3 AZ in the region.
The ASG is now configured to start instance in any of these AZ and is waiting for the routing to be completely setup.

Add subnets per AZ

---

cloudformation/main.yaml
modules/scanning-delegate-role/main.tf
modules/vpc/main.tf

This PR add 2 permissions:
* `kms:Decrypt`: this is required to read the snapshots that have been encrypted.
* `kms:DescribeKey`: this is required to find the key used by the snapshot.

Add IAM permission to allow decrypting snapshots using CMK

---

CHANGELOG.md
cloudformation/main.yaml
modules/user_data/main.tf

This change bumps `agentless-scanner` version to `7.53.0-agentless-scanner-2024032202`.

Bump agentless-scanner version to 7.53.0-agentless-scanner-2024032202

---

cloudformation/main.yaml
modules/scanning-delegate-role/main.tf

This PR adds in the orchestrator policy the ability to `kms:CreateGrant` (limited by `kms:GrantIsForAWSResource`) in order to be able to copy snapshots encrypted with customer-managed keys.
This should solve the following error:
```
waiting for copied snapshot "arn:aws:ec2:xxx:xxx:snapshot/snap-xxx": snapshot "snap-xxx" failed: Given key ID is not accessible
```
Note that we're NOT adding this capability to the worker policy. This is a permission that only apply for the write-only orchestrator.

Encrypted snapshots: allow granting KMS keys for AWS resources

---

cloudformation/main.yaml
modules/user_data/main.tf
modules/user_data/templates/install.sh.tftpl

- rely on APT to install the datadog-agentless-scanner package
- install the latest version matching the pinned MAJOR.MINOR version
- upgrade datadog-agent to 7.53.0
- remove the RC staging root keys from user_data

Auto-update the datadog-agentless-scanner package

---

cloudformation/main.yaml
modules/scanning-delegate-role/main.tf

Add permissions to scan lambda layers for Datadog/datadog-agentless-scanner#8

aws: lambda: add layer scanning perms

---

cloudformation/main.yaml
modules/scanning-delegate-role/README.md
modules/scanning-delegate-role/main.tf
modules/scanning-delegate-role/variables.tf

Add opt-ins to allow accessing AWS datastores like S3 buckets.

Add access to s3 buckets for DSPM

---

modules/azure/main.tf
modules/azure/provider.tf
modules/azure/variables.tf

Use the `azapi` provider to handle KV secrets in a better way:
1. User applying the TF no longer needs Key Vault Secrets User role and the secret is not stored in TF state
3. Only need to specify one variable (secret resource ID) instead of two (vault ID and secret name)

Azure: improve Key Vault secret handling

---

modules/agentless-scanner-role/variables.tf

Making sure the scanner's instance role is able to access at least one API key.

TF: add validation on api_key_secret_arns to be non-empty

---

modules/azure/custom-data/README.md
modules/azure/custom-data/main.tf
modules/azure/custom-data/templates/install.sh.tftpl
modules/azure/custom-data/variables.tf

Staying in sync with our AWS user_data allowing to use a beta channel.

Add `scanner_channel` parameter in Azure

---

cloudformation/main.yaml
modules/azure/custom-data/README.md
modules/azure/custom-data/main.tf
modules/azure/custom-data/outputs.tf
modules/azure/custom-data/templates/install.sh.tftpl
modules/user_data/README.md
modules/user_data/main.tf
modules/user_data/outputs.tf
modules/user_data/templates/install.sh.tftpl

Let's not pin to a specific minor version of the Agent and also activate auto-upgrade for this component.

Do not pin to a specific agent minror version to allow auto-upgrade

---

modules/user_data/templates/install.sh.tftpl

Avoids printing faulty empty object map `{}` in the configuration if no custom configuration was passed.
`yamlencode({})` is `{}`

Check custom configuration length before printing

---

modules/azure/CHANGELOG.md
modules/azure/virtual-machine/README.md
modules/azure/virtual-machine/main.tf

The azurerm provider does not support `reimage_on_manual_upgrade` for
flexible orchestration scale sets. This makes for a pretty miserable
upgrade experience.
The differences between flexible and uniform scale sets are not super
relevant to us, so let's just switch to uniform for the time being.

Azure: enable reimaging of VMs on upgrade

---

modules/azure/CHANGELOG.md
modules/azure/virtual-machine/main.tf

We will reimage/replace the instance if it fails health checks for 10 minutes.
Once DataDog/datadog-agentless-scanner#54 (rich health states) is released, we can lower this to 5 minutes or so.

Azure: enable automatic instance repairs

---

modules/azure/custom-data/templates/install.sh.tftpl

Append the last 6 bytes of the VM UUID to prevent hostname collisions.

Azure: append VM ID to hostname

---

modules/azure/virtual-machine/main.tf

This gives the VM additional time to initialize.
Supported since scanner version 0.11.6.

Azure: use Rich Health States

---

.pre-commit-config.yaml
modules/azure/README.md
modules/azure/managed-identity/README.md
modules/azure/managed-identity/provider.tf
modules/azure/provider.tf
modules/azure/resource-group/README.md
modules/azure/resource-group/provider.tf
modules/azure/roles/README.md
modules/azure/roles/provider.tf
modules/azure/virtual-machine/README.md
modules/azure/virtual-machine/provider.tf
modules/azure/virtual-network/README.md
modules/azure/virtual-network/provider.tf

According to the [Terraform documentation](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#terraform-core-and-provider-versions):
> - Reusable modules should constrain only their minimum allowed versions of Terraform and providers, such as >= 0.12.0. This helps avoid known incompatibilities, while allowing the user of the module flexibility to upgrade to newer versions of Terraform without altering the module.
> - Root modules should use a ~> constraint to set both a lower and upper bound on versions for each provider they depend on.
The main module can be used as either a root module or a child module, so I opted to set only a minimum version there too.

Azure: declare minimum provider versions only

---

modules/azure/custom-data/templates/install.sh.tftpl

`api_key` is a template variable, not a shell variable.

Azure: fix custom-data template bug

---

README.md
modules/azure/README.md
modules/azure/custom-data/README.md
modules/azure/custom-data/main.tf
modules/azure/custom-data/variables.tf
modules/azure/main.tf
modules/azure/variables.tf
variables.tf

Pass more options to custom-data:
- scanner_channel
- scanner_version
- scanner_configuration
- agent_configuration

Azure: additional configuration options in main module

---

modules/azure/CHANGELOG.md
modules/azure/custom-data/templates/install.sh.tftpl
modules/user_data/templates/install.sh.tftpl

There is no `deb` package for `semgrep`, so the options are to install it using `snap` or `pip`.
`pip` is not installed by default in Ubuntu Server and depends on `build-essential`, so a `snap` install is definitely going to be faster.
I used the `--no-wait` flag to install it in the background. Otherwise it takes around 20 seconds (tested on an Azure [Standard_B2ps_v2](https://learn.microsoft.com/azure/virtual-machines/sizes/general-purpose/bpsv2-series)).

Install semgrep

---

modules/scanning-delegate-role/main.tf

This PR add the following permission:
* to tag AMI when making a copy
* to make a copy of any ami
* to deregister the copy created
This is needed in order to scan ami that are shared with the scanned account.
The AMI can be used and copied but the underlying snapshot might not be.
See scanner changes here: https://github.com/DataDog/datadog-agentless-scanner/pull/96/files

Add permission to copy ami

---

modules/scanning-delegate-role/main.tf

We need to be able to read and copy from snapshots originating from CreateSnapshot. When reaching for these snapshots the `kms:EncryptionContext` for key `aws:ebs:id` is the originating volume.
reference: https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/services-ebs.md#amazon-ebs-encryption-context

Allow scanning volumes with customer-managed-key

---

CHANGELOG.md
README.md
main.tf
variables.tf

Adding `instance_type` and `instance_count` variables for AWS main module to allow configuring the ASG.

Allow specificy ASG parameters instance_type and instance_count from main module

---

README.md
examples/custom_agent_configurations/README.md
examples/custom_agent_configurations/main.tf
examples/custom_agent_configurations/variables.tf
modules/user_data/README.md
modules/user_data/variables.tf
variables.tf

This PR adds examples to provide extended configurations for the agent.
It also adds conditions on the provided agent_configuration to make sure certain fields cannot be overriden (api_key, hostname, site etc.)

docs: add example of extended agent configuration

---

CHANGELOG.md
README.md
examples/cross_account/README.md
examples/cross_account/scanner_account/main.tf
examples/cross_account/scanner_account/variables.tf
examples/custom_agent_configurations/main.tf
examples/custom_vpc/main.tf
examples/multi_region/main.tf
examples/single_region/main.tf
modules/agentless-scanner-role/README.md
modules/agentless-scanner-role/main.tf
modules/agentless-scanner-role/variables.tf
modules/scanning-delegate-role/README.md
modules/scanning-delegate-role/main.tf
modules/scanning-delegate-role/variables.tf

In order to simplify the deployment of our role delegation system this PR introduces the following changes:
1. scanner role: rely on a wildcard for account ID to allow adding new delegate role without having to provide their full ARN explicitly and instead relying on a naming convention. The `account_roles` variable can still be provided to enforce a specific list of roles to assume, but it defaults to `arn:*:iam::*:role/DatadogAgentlessScannerDelegateRole`
2. scanner role: allow specifying `organizational_unit_ids` to lock down the assumable roles to specific OUs.
3. delegate role: allow specifying `scanner_organizational_unit_ids` to lock down the originating OUs of scanner roles in the trust relationship.

Scanner role delegations based on a account_id wildcard by default

---

modules/agentless-scanner-role/README.md
modules/agentless-scanner-role/main.tf
modules/agentless-scanner-role/variables.tf

Rever part of #150. 
Field `allowed_organizational_unit_ids` was intended to rely on `aws:ResourceOrgID` instead of `aws:PrincipalOrgID`. But this global condition key `aws:ResourceOrgID` is not available for `AssumeRole`

Remove allowed_organizational_unit_ids

---

CHANGELOG.md
modules/agentless-scanner-role/README.md
modules/agentless-scanner-role/main.tf
modules/agentless-scanner-role/variables.tf

This PR introduces a new optional `account_org_paths` to the scanner role. This new variable can be used to enforce that the scanner can only reach for roles in the specified organisational unit paths.
Now that the `account_roles` is optional and defaults to a wildcard allowing to assume roles from any account, to limit the scope of the scanner role, without losing the convenience of specifying a account wildcard.

Introducing `account_org_paths` to limit the reachable accounts by OU path

---

azure/modules/custom-data/templates/install.sh.tftpl
modules/user_data/templates/install.sh.tftpl

Currently the agent is started automatically by the install script, before we set up its configuration files.
We later restart it to pick up the configuration changes, but it is faster and more reliable to only start it once the configuration is in place.

Prevent the agent from starting before it has been configured

---

variables.tf

In order to allow more complex filtering based on the scanner version, let's allow to give more precision to the scanner_version and only enforce that it starts with `X.Y`.

Relax the scanner_version condition

---

modules/user_data/variables.tf

Followup on #161. Missing the relaxation of the validation in the user_data module.

Relax the scanner_version condition in user_data module

---

examples/rds_scanning/main.tf
modules/agentless-s3-bucket/README.md
modules/agentless-s3-bucket/main.tf
modules/agentless-s3-bucket/variables.tf
modules/scanning-delegate-role/README.md
modules/scanning-delegate-role/main.tf
modules/scanning-delegate-role/outputs.tf

Move the KMS Key that used to be created in the delegate role out of the IAM module into the S3 Bucket Module.
There will be a KMS Key for each region we deploy the bucket to.

[SEC-17144] Move KMS Key to the S3 Module

---

README.md
main.tf
modules/user_data/README.md
modules/user_data/main.tf
modules/user_data/templates/install.sh.tftpl
modules/user_data/variables.tf
variables.tf

Adds a new `scanner_repository` variable to main and user_data modules. This parameter is used as the URL of the APT repository from which we fetch our scanner releases. Defaults to  `https://apt.datadoghq.com/`.

Add scanner_repository to specify host of the APT repository

---

azure/modules/custom-data/variables.tf
azure/variables.tf

Let's sync with how our AWS module works. This allows passing more complex conditions on the versions installed.

azure: relax condition on scan_version variable

---

modules/agentless-s3-bucket/main.tf

To deploy to production, we need to allow the HeadBucket action to the role used by TF:
https://gitlab.ddbuild.io/DataDog/cloud-inventory/-/jobs/732992334
> Error: reading S3 Bucket (datadog-agentless-scanning-20241210143920542100000001): operation error S3: HeadBucket, https response error StatusCode: 403, RequestID: DQF66JMRJYHQ42KE, HostID: 6GU95QuHjrKmnF4+5MWe50iR5lGa8WQQ4ADeHn2mvIHrio5ewRL3jSDAfYbhd9hyVS1J+Dv2RvhrU14GahyBMsmn6mIqwq2d73mjJ9MT1Ak=, api error Forbidden: Forbidden

[SEC-17145] Remove ListBucket from Denied actions in S3 bucket

---

.pre-commit-config.yaml

The Bicep CLI version in CI is updated periodically. We need to ensure that we run the pre-commit hook with the same version that was originally used to build the template, otherwise there will always be changes and the pre-commit hook will fail.
We can get the exact version used from `.metadata._generator.version` in the template itself. However, `az bicep install` expects the version to be passed in a different format: only the first three components and with a `v` prefix. We use `jq` to convert it to the expected format.

Fix Bicep pre-commit hook

---

modules/instance/README.md
modules/instance/variables.tf
modules/user_data/templates/install.sh.tftpl

This change uses Ubuntu 24.04 Minimal Server image instead of Ubuntu 24.04 Server image on AWS.
This provides a smaller Ubuntu installation, which should decrease the amount of known vulnerabilities.

Use Ubuntu 24.04 Minimal Server image on AWS

---

modules/user_data/templates/install.sh.tftpl

This change runs unattended upgrade on deployment on AWS.
It should allow the Agentless Scanner instance to get the most recent security fixes since the last published image.

Run unattended upgrade on deployment on AWS

---

azure/arm/agentless-api-call.ps1
azure/arm/main.bicep
azure/arm/main.json

Call the Datadog Agentless Scanning API at deployment time to automatically enable scanning for the subscriptions selected during the deployment.
For now this is not exposed in the ARM UI, in order to avoid having to specify an application key manually.

azure/arm: call Agentless API on deployment

---

README.md
modules/agentless-scanners-autoscaling/README.md
modules/agentless-scanners-autoscaling/main.tf
modules/agentless-scanners-autoscaling/outputs.tf
modules/agentless-scanners-autoscaling/provider.tf
modules/agentless-scanners-autoscaling/variables.tf
modules/instance/README.md
modules/instance/main.tf
modules/instance/variables.tf
variables.tf

Add Agentless Scanners autoscaling module. 
This module attaches the AutoScaling policy to the Datadog Integration Role that was used to onboard the scanners' AWS account to Datadog.

[AUTOSCALING] Add Agentless Scanners autoscaling module

---

modules/scanning-delegate-role/main.tf

reference: https://aws.amazon.com/blogs/storage/enhancing-resource-level-permissions-for-copying-amazon-ebs-snapshots/

Adapt CopySnapshot policy to latest IAM changes

---

CHANGELOG.md
azure/arm/main.json
azure/modules/custom-data/templates/install.sh.tftpl
modules/user_data/templates/install.sh.tftpl

Update the CHANGELOG for preparing the v0.11.11 release.
Also backfill the CHANGELOG for v0.11.10.

release: update CHANGELOG for prep of 0.11.11

---

.pre-commit-config.yaml

We need to run this hook not just when the main template changes, but also whenever any of the template inputs change, including the scripts.
To simplify (and future-proof) things, let's run the hook whenever any of the files in this directory change (except the README).
I also combined the azure-install and azure-build hooks because they always need to run together anyway.

Rework Bicep pre-commit hook

---

gcp/README.md
gcp/modules/agentless-impersonated-service-account/README.md
gcp/modules/agentless-scanner-service-account/README.md
gcp/modules/instance/README.md
gcp/modules/vpc/README.md

Generate markdown documentation and TF docs for Agentless Scanning GCP modules.

[K9VULN-7306] [Agentless] Add documentation and TF docs for GCP modules

---

.pre-commit-config.yaml
gcp/README.md
gcp/modules/agentless-impersonated-service-account/README.md
gcp/modules/agentless-impersonated-service-account/main.tf
gcp/modules/agentless-impersonated-service-account/outputs.tf
gcp/modules/agentless-scanner-service-account/README.md
gcp/modules/instance/README.md
gcp/modules/vpc/README.md
gcp/outputs.tf

First commit adds the binding on the `roles/artifactregistry.reader` predefined role for our target service account.
Second commit adds the GCP modules in our pre-commit configuration.

gcp: bind Artifact Registry readonly access

---

gcp/README.md
gcp/main.tf
gcp/modules/agentless-scanner-service-account/README.md
gcp/modules/agentless-scanner-service-account/main.tf
gcp/modules/agentless-scanner-service-account/variables.tf
gcp/modules/instance/README.md
gcp/modules/instance/main.tf
gcp/modules/instance/provider.tf
gcp/modules/instance/variables.tf
gcp/modules/vpc/README.md
gcp/modules/vpc/outputs.tf
gcp/modules/vpc/variables.tf
gcp/outputs.tf
gcp/provider.tf
gcp/variables.tf

What?
=====
- remove vpc module's duplicated output (`subnetwork_name`)
- make `api_key` variable optional and check that only one of (`api_key`, `api_key_secret_id `)
- homogenize `api_key_secret_id ` between all modules (long id instead of secret name)
- disable ssh access by default
Why?
=====
- for better homogeneity and clarity

[K9VULN-8680] fix(gcp): homogenize variables inputs/outputs between all modules
